wowserhq/spelunker

- packages/spelunker-api/src/lib/entities/Item.mjs
- packages/spelunker-api/src/lib/entities/ItemSet.mjs
- packages/spelunker-api/src/lib/graph/root.mjs
- packages/spelunker-api/src/lib/graph/schema/QueryType.mjs
- packages/spelunker-api/src/lib/graph/schema/entities/ItemSetType.mjs
- packages/spelunker-api/src/lib/graph/schema/entities/ItemType.mjs
- packages/spelunker-web/src/components/Search/ResultsTab.jsx
- packages/spelunker-web/src/components/Search/index.jsx
- packages/spelunker-web/src/components/Spelunker/index.jsx
- packages/spelunker-web/src/components/entities/Item/index.jsx
- packages/spelunker-web/src/components/entities/ItemSet/List.jsx
- packages/spelunker-web/src/components/entities/ItemSet/Reference/index.jsx
- packages/spelunker-web/src/components/entities/ItemSet/columns/ReferenceColumn.jsx
- packages/spelunker-web/src/components/entities/ItemSet/columns/index.jsx
- packages/spelunker-web/src/components/entities/ItemSet/index.jsx
This PR implements the bare minimum for item sets. In the future we should look into rendering out benefits gained as well.
**Listing item sets**:
**Viewing an individual item set**:
**An item part of a set**:
Currently a bit unsure where the quality / color from an item set comes from. Thoughts @fallenoak?
> Feature: Item sets

- packages/spelunker-api/package-lock.json
- packages/spelunker-api/package.json
This PR updates the version of Blizzardry used to v0.5.1, which adds support for versions of Node >= 10.
> chore: update blizzardry to support node 10+

- packages/spelunker-api/package-lock.json
- packages/spelunker-api/package.json
This PR brings the set of dev dependencies used in `spelunker-api` up to the latest versions.
> chore: update api dev dependencies

- packages/spelunker-api/package-lock.json
- packages/spelunker-api/package.json
- packages/spelunker-api/src/lib/server.mjs
This PR updates several `spelunker-api` runtime dependencies:
- `apollo-server` is now at 2.x, which includes GraphQL Playground as an alternative to GraphiQL
- `mysql` is now on its current version, which fixes a few timeout issues on recent Node versions
- Various other dependencies are now on much newer versions, making it easier to move to their latest versions
> chore: update api runtime dependencies

- packages/spelunker-web/src/components/entities/Side/index.jsx
- packages/spelunker-web/src/components/entities/Side/tabs/Areas.jsx
- packages/spelunker-web/src/components/entities/Side/tabs/ExclusiveQuests.jsx
- packages/spelunker-web/src/components/entities/Side/tabs/Quests.jsx
- packages/spelunker-web/src/components/entities/Side/tabs/Races.jsx
I was a little hasty in converting `id` route params to integers. It turns out we had one use of them as strings.
> fix(web): use string type for side id

- packages/spelunker-api/package-lock.json
- packages/spelunker-api/package.json
- packages/spelunker-api/src/lib/db/connections.mjs
MySQL 8.x appears to be gaining some steam as the successor to MySQL 5.7. It changes the default auth mechanism to `caching_sha2_password`, which `mysql` doesn't currently support. See PR here: https://github.com/mysqljs/mysql/pull/2233
The `mysql2` driver does support this new MySQL 8.x auth mechanism. Fortunately, `knex` supports both `mysql` and `mysql2` out of the box! I've been driving it around locally and it appears to work well.
> chore: switch api db connections to mysql2

- .github/workflows/api-ci.yml
This PR introduces a CI workflow for `spelunker-api`. We don't have any tests currently, but it does install dependencies, and runs the `lint` script.
> chore(ci): add ci workflow for spelunker-api

- packages/spelunker-web/.eslintrc
This PR tweaks the `camelcase` ESLint rule to permit `UNSAFE`-prefixed function names (a la `UNSAFE_componentWillMount`).
> chore(format): allow UNSAFE-prefixed functions in camelcase eslint rule

- packages/spelunker-web/package-lock.json
- packages/spelunker-web/package.json
This PR updates our `spelunker-web` GraphQL dependency from 14.x to the latest 15.x release. Apollo Client is compatible with both 14.x and 15.x.
> chore(web): update graphql dependency

- packages/spelunker-web/babel.config.json
- packages/spelunker-web/package-lock.json
- packages/spelunker-web/package.json
This PR upgrades our use of Babel in `spelunker-web` from 6.x to 7.x.
> chore(web): upgrade to babel 7

- packages/spelunker-web/babel.config.json
We were still allowing `ie_mob` in, which ended up turning on a bunch of unnecessary transforms.
*Before*
```
Using plugins:
proposal-class-static-block { ie, ios, node < 16.11, safari, samsung }
proposal-private-property-in-object { ie, ios < 15, node < 16.9, samsung }
proposal-class-properties { ie, ios < 15, node < 14.6 }
proposal-private-methods { ie, ios < 15, node < 14.6 }
proposal-numeric-separator { ie }
proposal-logical-assignment-operators { ie, node < 15 }
proposal-nullish-coalescing-operator { ie, node < 14 }
proposal-optional-chaining { ie, node < 16.9, samsung }
proposal-json-strings { ie }
proposal-optional-catch-binding { ie }
transform-parameters { ie, ios, safari }
proposal-async-generator-functions { ie }
proposal-object-rest-spread { ie }
transform-dotall-regex { ie } …
```
> chore(web): exclude ie_mob from babel targets

- packages/spelunker-web/.gitignore
Webpack produces `.js.map` files when running builds. This PR keeps us from inadvertently putting them in source control.
> chore(web): ignore .js.map files in the build output directory

- packages/spelunker-web/.eslintrc
This PR enables support for ES2020 language features (like nullish coalescing) for `spelunker-web` in the ESLint parser. Babel already supports these features.
> chore(web): enable es2020 support in eslint

- .github/workflows/web-ci.yml
- packages/spelunker-web/package-lock.json
- packages/spelunker-web/package.json
- packages/spelunker-web/webpack.config.js
This PR upgrades `spelunker-web` to webpack 5.x, and brings all of the webpack dependencies up to their latest versions as well. This should close out most of the open security warnings for `spelunker-web`.
> chore(web): upgrade to webpack 5

- packages/spelunker-web/src/components/Spelunker/graphql-client.js
- packages/spelunker-web/src/utils/graphql.js
- packages/spelunker-web/src/utils/policies/collection.js
- packages/spelunker-web/src/utils/policies/index.js
This PR introduces a special type policy generator for our `CollectionType`. This permits clean merges for data, while still allowing lazy loads and arbitrary offset windowing.
> feat(web): add type policy generator for CollectionType

- packages/spelunker-web/package-lock.json
- packages/spelunker-web/package.json
- packages/spelunker-web/src/components/Spelunker/graphql-client.js
This PR kicks on automatic persisted queries for our Apollo client in `spelunker-web`. It also enables the persisted queries to operate via `GET` requests, giving us options for CDN caching of responses.
> feat(web): enable persisted queries

- packages/spelunker-web/.gitignore
- packages/spelunker-web/package-lock.json
- packages/spelunker-web/package.json
- packages/spelunker-web/webpack.config.js
This PR moves static webpack build outputs from `/public` to `/public/static`, split by `js` and `img`. It also drops `url-loader` in favor of webpack 5's built in asset modules.
This PR keeps `html-webpack-plugin`'s `index.html` output in the root of `/public`.
These changes will make it simple for us to define long-term caching policies for our content hashed build outputs, while keeping the entrypoint `index.html` uncached.
> chore(web): separate build outputs

- packages/spelunker-api/src/lib/pipeline/index.mjs
- packages/spelunker-web/src/components/entities/Class/Icon/index.jsx
- packages/spelunker-web/src/components/entities/Race/Icon/index.jsx
- packages/spelunker-web/src/components/formatters/Currency/index.jsx
- packages/spelunker-web/src/components/images/GameIcon/index.jsx
- packages/spelunker-web/src/components/images/GameImage/index.jsx
- packages/spelunker-web/src/components/images/QuestgiverIcon.jsx
- packages/spelunker-web/src/utils/pipeline.js
This PR modifies the pipeline server to support serving resources requested with forward-slashed paths `/` instead of the MPQ standard of backward-slashed paths `\`.
This PR also normalizes web client paths to always be forward-slashed `/` and lowercase (MPQ file lookups are case insensitive).
This hopefully makes it a bit easier to work with pipeline resources, and improves cache hit rates by preventing case mismatches from creating unique paths.
> feat: normalize pipeline paths

- packages/spelunker-api/src/lib/pipeline/index.mjs
- packages/spelunker-web/src/components/images/GameImage/index.jsx
This PR adjusts our file requests to the pipeline to look for files under a `/files` prefix. This helps keep the root of the pipeline endpoints clean, in the event we start to add new helper-style endpoints like `/minimap`.
> chore: make pipeline files endpoint distinct

- .github/workflows/web-ci.yml
- packages/spelunker-web/package-lock.json
- packages/spelunker-web/package.json
- packages/spelunker-web/src/components/entities/Class/Icon/index.styl
- packages/spelunker-web/src/components/entities/Race/Icon/index.styl
- packages/spelunker-web/src/components/images/GameImage/index.jsx
- packages/spelunker-web/src/components/images/GameImage/index.styl
- packages/spelunker-web/webpack.config.js
This PR introduces `Blp` from `@wowserhq/format` to permit `GameIcon`, `ClassIcon`, and `RaceIcon` to render icons without relying on PNGs converted from the the BLPs. This allows Spelunker to directly consume art assets hosted at `DATA_URI`.
> feat: render icons from BLPs directly

- packages/spelunker-web/src/components/core/GameMap/index.jsx
- packages/spelunker-web/src/components/images/GameImage/index.jsx
- packages/spelunker-web/src/utils/blp.js
This PR switches `GameMap` over to using `Blp` from `@wowserhq/format` to directly render `.blp` minimap tiles, dropping the slow PNG conversion path via the pipeline server.
> feat(web): improve rendering performance of maps

- packages/spelunker-api/src/lib/entities/Item.mjs
- packages/spelunker-api/src/lib/entities/ItemClass.mjs
- packages/spelunker-api/src/lib/graph/schema/entities/ItemClassType.mjs
- packages/spelunker-api/src/lib/graph/schema/entities/ItemType.mjs
This PR extends items with item classes.
> feat: add ItemClass entity and object type

- packages/spelunker-api/src/lib/core/Query.mjs
- packages/spelunker-api/src/lib/entities/Item.mjs
- packages/spelunker-api/src/lib/graph/root.mjs
- packages/spelunker-api/src/lib/graph/schema/QueryType.mjs
This PR introduces the ability to filter items by one or more item classes.
For example:
```
query ExampleQuery {
items(searchQuery: "torment", itemClassIds: [2, 3]) {
results {
id, name, itemClass { id, name }
}
}
}
```
returns:
```
{
"data": {
"items": {
"results": [
{
"id": 25806,
"name": "Nethekurse's Rod of Torment",
"itemClass": {
"id": 2,
"name": "Weapon"
}
},
{
"id": 39291,
"name": "Torment of the Banished",
"itemClass": {
"id": 2,
"name": "Weapon"
}
}
]
}
}
}
```
The PR introduces the notion of `filters` separate from `search`: `search` permits entering an entity name for a partial string match (as it already does today), while `filters` support type-and-field-specific equality checks. The collection level entities in the root of the schema would support both `searchQuery` and …
> feat(api): support filtering items by item class
